#!/bin/sh
# There is a long list of grandfathered allowed warnings in here.
# The goal is to whittle these down over time while preventing new regressions.
html5validator \
  --skip-non-html \
  --ignore \
  "An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images."\
  "Element “style” not allowed as child of element “article” in this context. (Suppressing further errors from this subtree.)"\
  "Row 2 of a row group established by a “tbody” element has no cells beginning on it."\
  "Row 4 of a row group established by a “tbody” element has no cells beginning on it."\
  "The “align” attribute on the “p” element is obsolete. Use CSS instead."\
  "The “align” attribute on the “table” element is obsolete. Use CSS instead."\
  "The “align” attribute on the “td” element is obsolete. Use CSS instead."\
  "The “align” attribute on the “th” element is obsolete. Use CSS instead."\
  "The “align” attribute on the “tr” element is obsolete. Use CSS instead."\
  "The “bgcolor” attribute on the “td” element is obsolete. Use CSS instead."\
  "The “border” attribute on the “table” element is obsolete. Use CSS instead."\
  "The “center” element is obsolete. Use CSS instead."\
  "The “font” element is obsolete. Use CSS instead."\
  "The “hspace” attribute on the “img” element is obsolete. Use CSS instead."\
  "The “vspace” attribute on the “img” element is obsolete. Use CSS instead."\
  --root public/
